baseURL = "https://paulrobben.de"
languageCode = "de-de"
theme = "adritian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

#  [[menu.header]]
#  name = "Portfolio"
#  URL = "#portfolio"
#  weight = 3

#  [[menu.header]]
#  name = "Experience"
#  URL = "#experience"
#  weight = 4

  [[menu.header]]
  name = "Blog"
  URL = "/blog"
  weight = 5

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 6

  [[menu.footer]]
  name = "Code on Github"
  URL = "https://github.com/paulrobben/paulrobben.de"
  weight = 1



[params]

  sections = ["showcase", "about", "photos", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  homepageExperienceCount = 6

  # controls vercel page insights - disabled by default
  vercelPageInsights = false
  vercelAnalytics = false

  [params.google_analytics]
      code = "UA-XXXXX-Y"
      enabled = false
  [params.google_tag_manager]
      code = "GTM-XXXXX"
      enabled = false

  [params.logo]
    text1 = "Paul"
    text2 = "Robben"

  [params.footer]
      copyright = "© Paul Robben. Free Hugo theme by Adrián Moreno Peña."
